name: Install Environment and Run Tests

on:
  push:
    branches: master
  pull_request:
jobs:
  install-and-test:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      # Our workflows were running out of memory.  We don't need most of the pre-installed machinery in the
      # github ubuntu image, so remove it using this helper action.
      # See: https://github.com/marketplace/actions/free-disk-space-ubuntu
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Checkout the Squid repo
        uses: actions/checkout@v4
      - name: Run the setup script for Ubuntu 22.04
        run: ./setup_22.04.sh -r=${{ github.workspace }}
        working-directory: ./software
      - name: Run the cuda setup script
        run: ./setup_cuda_22.04.sh
        working-directory: ./software
      - name: "Copy a valid config into the repo software root"
        run: cp configurations/configuration_Squid+.ini .
        working-directory: ./software
      - name: Run the tests
        run: python3 -m pytest
        working-directory: ./software
